
# - platform: ddwrt
  # host: !secret router_ip_address
  # username: !secret router_username
  # password: !secret router_password
  # interval_seconds: 10
  # consider_home: 180
  # new_device_defaults:
    # track_new_devices: False
- platform: netgear
  host: !secret router_ip_address
  username: !secret router_username
  password: !secret router_password
  interval_seconds: 10
  consider_home: 120
  new_device_defaults:
    track_new_devices: True
    hide_if_away: False
    

# - platform: nmap_tracker
  # hosts: 192.168.0.0-255
  # consider_home: 120
  # new_device_defaults:
    # track_new_devices: True
    # hide_if_away: False
  