###############################################################################
#   @author         :   J.Illes
#   @date           :   08/18/2018
#   @package        :   
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
  customize:

group:

input_number:

input_select:

sensor:

###############################################################################
#                               Automations
###############################################################################
automation: